--- #YAML:1.0
name:                LWP-Authen-Negotiate
version:             0.08
abstract:            GSSAPI based Authentication Plugin for LWP
license:             ~
author:              
    - Achim Grolms <perl@grolmsnet.de>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    GSSAPI:                        0.18
    LWP::Debug:                    0
    MIME::Base64:                  2.12
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
